{% set VERSION_SUFFIX = "" %} # debug version suffix, appended to the version

package:
  name: numba-scfg
  # GIT_DESCRIBE_TAG may not be set
  version: {{ "%s%s" % (environ.get('GIT_DESCRIBE_TAG', ''), VERSION_SUFFIX) }}

source:
  # Using the local source tree helps test building without pushing changes
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  string: {{ GIT_BUILD_STR }}

requirements:
  host:
    - python >=3.11
    - setuptools
    - pip
  run:
    - python >=3.11
    - python-graphviz
    - pyyaml

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs numba_scfg

about:
  summary: Numba Compatible SCFG utilities
  home: https://github.com/numba/numba-scfg
  license: Simplified BSD License
  license_file: LICENSE
