{% set VERSION_SUFFIX = "" %} # debug version suffix, appended to the version

package:
  name: numba_rvsdg
  # GIT_DESCRIBE_TAG may not be set
  version: {{ "%s%s" % (environ.get('GIT_DESCRIBE_TAG', '').lstrip('v'), VERSION_SUFFIX) }}

source:
  # Using the local source tree helps test building without pushing changes
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  
requirements:
  build:
    - python
    - setuptools
  run:
    - python >=3.11
    - python-graphviz
    - pyyaml

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs numba_rvsdg

about:
  home: https://github.com/numba/numba_rvsdg
  license: New BSD License
  summary: TBD
