name: Test

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install graphviz python=3.11
          pip install pytest pyyaml graphviz coverage
      - name: Setup numba_rvsdg
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: Run pytest and Generate Report
        shell: bash -l {0}
        run: |
          coverage run -m pytest numba_rvsdg/tests/
      - name: Display Coverage
        shell: bash -l {0}
        run: |
          coverage report

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install python=3.11 mypy pyyaml graphviz
          pip install types-PyYAML

      - name: Run mypy
        shell: bash -l {0}
        run: |
          mypy .
